name: tsafer
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.3.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: SF300
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Light.ttf
    - family: SF400
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
    - family: SF500
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.ttf
    - family: SF600
      fonts:
        - asset: assets/fonts/SF-Pro-Display-SemiBold.ttf
    - family: SF700
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
    - family: SF800
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Heavy.ttf
    - family: SF900
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.ttf